const markerTemplates = {
  "arkoniden_standard": "\n<div class=\"marker arkoniden_standard\">\n  <div class=\"marker-top\">\n    <img src=\"icons/arkoniden_symbol.png\" class=\"fraktionssymbol\">\n    <img src=\"icons/chevron_veteran.png\" class=\"chevron\">\n  </div>\n  <div class=\"marker-main\">\n    <img src=\"icons/kugelraumer.png\" class=\"unit-symbol\">\n    <span class=\"angriffswert\">18</span>\n    <span class=\"verteidigungswert\">22</span>\n  </div>\n  <div class=\"marker-lp\">\n    <span class=\"lp-strich\">|</span><span class=\"lp-strich\">|</span>\n  </div>\n  <div class=\"marker-name\">17. LIG</div>\n</div>\n",
  "arkoniden_admiral": "\n<div class=\"marker arkoniden_admiral\">\n  <div class=\"marker-header\">\n    <img src=\"icons/arkoniden_symbol.png\" class=\"fraktionssymbol\">\n    <span class=\"admiral-name\">Atlan</span>\n    <span class=\"admiral-rang\">3 Sonnentr\u00e4ger</span>\n  </div>\n  <div class=\"admiral-portrait\">\n    <img src=\"portraits/atlan.png\" class=\"portrait-img\">\n  </div>\n  <div class=\"admiral-werte\">\n    <span class=\"kommandowert\">4</span>\n    <span class=\"bonuswert\">+4</span>\n  </div>\n</div>\n",
  "arkoniden_raumfort": "\n<div class=\"marker arkoniden_raumfort\">\n  <div class=\"marker-top\">\n    <img src=\"icons/arkoniden_symbol.png\" class=\"fraktionssymbol\">\n    <img src=\"icons/chevron_regulaer.png\" class=\"chevron\">\n  </div>\n  <div class=\"marker-main\">\n    <img src=\"icons/raumfort_hex.png\" class=\"unit-symbol\">\n    <span class=\"angriffswert\">10</span>\n    <span class=\"verteidigungswert\">12</span>\n  </div>\n  <div class=\"marker-lp\">\n    <span class=\"lp-strich\">|</span><span class=\"lp-strich\">|</span><span class=\"lp-strich\">|</span>\n  </div>\n  <div class=\"marker-name\">7. RAUMFORT</div>\n</div>\n",
  "maahks_standard": "\n<div class=\"marker maahks_standard\">\n  <div class=\"marker-top\">\n    <img src=\"icons/maahks_symbol.png\" class=\"fraktionssymbol\">\n    <img src=\"icons/chevron_veteran.png\" class=\"chevron\">\n  </div>\n  <div class=\"marker-main\">\n    <img src=\"icons/walzenraumer.png\" class=\"unit-symbol\">\n    <span class=\"angriffswert\">9</span>\n    <span class=\"verteidigungswert\">12</span>\n  </div>\n  <div class=\"marker-lp\">\n    <span class=\"lp-strich\">|</span><span class=\"lp-strich\">|</span>\n  </div>\n  <div class=\"marker-name\">40. KREUZER</div>\n</div>\n",
  "maahks_jaeger": "\n<div class=\"marker maahks_jaeger\">\n  <div class=\"marker-top\">\n    <img src=\"icons/maahks_symbol.png\" class=\"fraktionssymbol\">\n    <span class=\"marker-type\">JGR</span>\n  </div>\n  <div class=\"marker-main\">\n    <img src=\"icons/jaeger_symbol.png\" class=\"unit-symbol-small\">\n    <span class=\"angriffswert klein\">1</span>\n    <span class=\"verteidigungswert klein\">1</span>\n  </div>\n</div>\n",
  "maahks_traeger": "\n<div class=\"marker maahks_traeger\">\n  <div class=\"marker-top\">\n    <img src=\"icons/maahks_symbol.png\" class=\"fraktionssymbol\">\n    <img src=\"icons/chevron_regulaer.png\" class=\"chevron\">\n  </div>\n  <div class=\"marker-main\">\n    <img src=\"icons/traeger_walze.png\" class=\"unit-symbol\">\n    <span class=\"angriffswert\">8</span>\n    <span class=\"verteidigungswert\">10</span>\n    <img src=\"icons/jaeger_symbol.png\" class=\"beladung-symbol\" title=\"J\u00e4ger an Bord\">\n  </div>\n  <div class=\"marker-lp\">\n    <span class=\"lp-strich\">|</span><span class=\"lp-strich\">|</span>\n  </div>\n  <div class=\"marker-name\">3. TR\u00c4GR</div>\n</div>\n",
  "maahks_admiral": "\n<div class=\"marker maahks_admiral\">\n  <div class=\"marker-header\">\n    <img src=\"icons/maahks_symbol.png\" class=\"fraktionssymbol\">\n    <span class=\"admiral-name\">Grek-1</span>\n    <span class=\"admiral-rang\">Rang 1</span>\n  </div>\n  <div class=\"admiral-portrait\">\n    <img src=\"portraits/grek1.png\" class=\"portrait-img\">\n  </div>\n  <div class=\"admiral-werte\">\n    <span class=\"kommandowert\">7</span>\n    <span class=\"bonuswert\">+2</span>\n  </div>\n</div>\n"
};

// Markerplatzierungslogik folgt in der Loader-HTML-Datei
